stages: 
  load_save_stage:
    cmd: python src/stage_01_load_and_save.py
    deps: 
      - src/stage_01_load_and_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs: 
      - artifacts/raw_local_dir/data.csv